<?php

/**
 * BaseChpuMain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $short
 * 
 * @method string   getUrl()   Returns the current record's "url" value
 * @method string   getShort() Returns the current record's "short" value
 * @method ChpuMain setUrl()   Sets the current record's "url" value
 * @method ChpuMain setShort() Sets the current record's "short" value
 * 
 * @package    online
 * @subpackage model
 * @author     Farrukh Umurzakov
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseChpuMain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chpu_main');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('short', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}