<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/11/23 00:31:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=chpu',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
